version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
      - "9929:9929"
      - "9230:9230"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - SNIPCART_API=${SNIPCART_API}
      - DATOCMS_API=${DATOCMS_API}
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/